package com.icss.bp.bean;

import java.util.Date;

public class BPDistLineBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_DIST_LINE.DL_ID
     *
     * @mbggenerated
     */
    private Long dlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_DIST_LINE.DL_UUID
     *
     * @mbggenerated
     */
    private String dlUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_DIST_LINE.DL_SORT_DATE
     *
     * @mbggenerated
     */
    private Date dlSortDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_DIST_LINE.DL_B_UUID
     *
     * @mbggenerated
     */
    private String dlBUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_DIST_LINE.DL_B_CODE
     *
     * @mbggenerated
     */
    private String dlBCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_DIST_LINE.DL_B_TYPE
     *
     * @mbggenerated
     */
    private String dlBType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_DIST_LINE.DL_CODE
     *
     * @mbggenerated
     */
    private String dlCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_DIST_LINE.DL_NAME
     *
     * @mbggenerated
     */
    private String dlName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_DIST_LINE.DL_SEQUENCE
     *
     * @mbggenerated
     */
    private Integer dlSequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_DIST_LINE.DL_ORDER_NUM
     *
     * @mbggenerated
     */
    private Integer dlOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_DIST_LINE.DL_PRINT_NUM
     *
     * @mbggenerated
     */
    private Integer dlPrintNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_DIST_LINE.DL_START_TIME
     *
     * @mbggenerated
     */
    private Date dlStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_DIST_LINE.DL_END_TIME
     *
     * @mbggenerated
     */
    private Date dlEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_DIST_LINE.DL_STATE
     *
     * @mbggenerated
     */
    private String dlState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_DIST_LINE.DL_SEND_STATE
     *
     * @mbggenerated
     */
    private String dlSendState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_DIST_LINE.DL_SELF_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date dlSelfUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_DIST_LINE.DL_SUB_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date dlSubUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_DIST_LINE.DL_ID
     *
     * @return the value of BP_DIST_LINE.DL_ID
     *
     * @mbggenerated
     */
    public Long getDlId() {
        return dlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_DIST_LINE.DL_ID
     *
     * @param dlId the value for BP_DIST_LINE.DL_ID
     *
     * @mbggenerated
     */
    public void setDlId(Long dlId) {
        this.dlId = dlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_DIST_LINE.DL_UUID
     *
     * @return the value of BP_DIST_LINE.DL_UUID
     *
     * @mbggenerated
     */
    public String getDlUuid() {
        return dlUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_DIST_LINE.DL_UUID
     *
     * @param dlUuid the value for BP_DIST_LINE.DL_UUID
     *
     * @mbggenerated
     */
    public void setDlUuid(String dlUuid) {
        this.dlUuid = dlUuid == null ? null : dlUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_DIST_LINE.DL_SORT_DATE
     *
     * @return the value of BP_DIST_LINE.DL_SORT_DATE
     *
     * @mbggenerated
     */
    public Date getDlSortDate() {
        return dlSortDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_DIST_LINE.DL_SORT_DATE
     *
     * @param dlSortDate the value for BP_DIST_LINE.DL_SORT_DATE
     *
     * @mbggenerated
     */
    public void setDlSortDate(Date dlSortDate) {
        this.dlSortDate = dlSortDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_DIST_LINE.DL_B_UUID
     *
     * @return the value of BP_DIST_LINE.DL_B_UUID
     *
     * @mbggenerated
     */
    public String getDlBUuid() {
        return dlBUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_DIST_LINE.DL_B_UUID
     *
     * @param dlBUuid the value for BP_DIST_LINE.DL_B_UUID
     *
     * @mbggenerated
     */
    public void setDlBUuid(String dlBUuid) {
        this.dlBUuid = dlBUuid == null ? null : dlBUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_DIST_LINE.DL_B_CODE
     *
     * @return the value of BP_DIST_LINE.DL_B_CODE
     *
     * @mbggenerated
     */
    public String getDlBCode() {
        return dlBCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_DIST_LINE.DL_B_CODE
     *
     * @param dlBCode the value for BP_DIST_LINE.DL_B_CODE
     *
     * @mbggenerated
     */
    public void setDlBCode(String dlBCode) {
        this.dlBCode = dlBCode == null ? null : dlBCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_DIST_LINE.DL_B_TYPE
     *
     * @return the value of BP_DIST_LINE.DL_B_TYPE
     *
     * @mbggenerated
     */
    public String getDlBType() {
        return dlBType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_DIST_LINE.DL_B_TYPE
     *
     * @param dlBType the value for BP_DIST_LINE.DL_B_TYPE
     *
     * @mbggenerated
     */
    public void setDlBType(String dlBType) {
        this.dlBType = dlBType == null ? null : dlBType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_DIST_LINE.DL_CODE
     *
     * @return the value of BP_DIST_LINE.DL_CODE
     *
     * @mbggenerated
     */
    public String getDlCode() {
        return dlCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_DIST_LINE.DL_CODE
     *
     * @param dlCode the value for BP_DIST_LINE.DL_CODE
     *
     * @mbggenerated
     */
    public void setDlCode(String dlCode) {
        this.dlCode = dlCode == null ? null : dlCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_DIST_LINE.DL_NAME
     *
     * @return the value of BP_DIST_LINE.DL_NAME
     *
     * @mbggenerated
     */
    public String getDlName() {
        return dlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_DIST_LINE.DL_NAME
     *
     * @param dlName the value for BP_DIST_LINE.DL_NAME
     *
     * @mbggenerated
     */
    public void setDlName(String dlName) {
        this.dlName = dlName == null ? null : dlName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_DIST_LINE.DL_SEQUENCE
     *
     * @return the value of BP_DIST_LINE.DL_SEQUENCE
     *
     * @mbggenerated
     */
    public Integer getDlSequence() {
        return dlSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_DIST_LINE.DL_SEQUENCE
     *
     * @param dlSequence the value for BP_DIST_LINE.DL_SEQUENCE
     *
     * @mbggenerated
     */
    public void setDlSequence(Integer dlSequence) {
        this.dlSequence = dlSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_DIST_LINE.DL_ORDER_NUM
     *
     * @return the value of BP_DIST_LINE.DL_ORDER_NUM
     *
     * @mbggenerated
     */
    public Integer getDlOrderNum() {
        return dlOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_DIST_LINE.DL_ORDER_NUM
     *
     * @param dlOrderNum the value for BP_DIST_LINE.DL_ORDER_NUM
     *
     * @mbggenerated
     */
    public void setDlOrderNum(Integer dlOrderNum) {
        this.dlOrderNum = dlOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_DIST_LINE.DL_PRINT_NUM
     *
     * @return the value of BP_DIST_LINE.DL_PRINT_NUM
     *
     * @mbggenerated
     */
    public Integer getDlPrintNum() {
        return dlPrintNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_DIST_LINE.DL_PRINT_NUM
     *
     * @param dlPrintNum the value for BP_DIST_LINE.DL_PRINT_NUM
     *
     * @mbggenerated
     */
    public void setDlPrintNum(Integer dlPrintNum) {
        this.dlPrintNum = dlPrintNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_DIST_LINE.DL_START_TIME
     *
     * @return the value of BP_DIST_LINE.DL_START_TIME
     *
     * @mbggenerated
     */
    public Date getDlStartTime() {
        return dlStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_DIST_LINE.DL_START_TIME
     *
     * @param dlStartTime the value for BP_DIST_LINE.DL_START_TIME
     *
     * @mbggenerated
     */
    public void setDlStartTime(Date dlStartTime) {
        this.dlStartTime = dlStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_DIST_LINE.DL_END_TIME
     *
     * @return the value of BP_DIST_LINE.DL_END_TIME
     *
     * @mbggenerated
     */
    public Date getDlEndTime() {
        return dlEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_DIST_LINE.DL_END_TIME
     *
     * @param dlEndTime the value for BP_DIST_LINE.DL_END_TIME
     *
     * @mbggenerated
     */
    public void setDlEndTime(Date dlEndTime) {
        this.dlEndTime = dlEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_DIST_LINE.DL_STATE
     *
     * @return the value of BP_DIST_LINE.DL_STATE
     *
     * @mbggenerated
     */
    public String getDlState() {
        return dlState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_DIST_LINE.DL_STATE
     *
     * @param dlState the value for BP_DIST_LINE.DL_STATE
     *
     * @mbggenerated
     */
    public void setDlState(String dlState) {
        this.dlState = dlState == null ? null : dlState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_DIST_LINE.DL_SEND_STATE
     *
     * @return the value of BP_DIST_LINE.DL_SEND_STATE
     *
     * @mbggenerated
     */
    public String getDlSendState() {
        return dlSendState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_DIST_LINE.DL_SEND_STATE
     *
     * @param dlSendState the value for BP_DIST_LINE.DL_SEND_STATE
     *
     * @mbggenerated
     */
    public void setDlSendState(String dlSendState) {
        this.dlSendState = dlSendState == null ? null : dlSendState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_DIST_LINE.DL_SELF_UPDATE_TIME
     *
     * @return the value of BP_DIST_LINE.DL_SELF_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getDlSelfUpdateTime() {
        return dlSelfUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_DIST_LINE.DL_SELF_UPDATE_TIME
     *
     * @param dlSelfUpdateTime the value for BP_DIST_LINE.DL_SELF_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setDlSelfUpdateTime(Date dlSelfUpdateTime) {
        this.dlSelfUpdateTime = dlSelfUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_DIST_LINE.DL_SUB_UPDATE_TIME
     *
     * @return the value of BP_DIST_LINE.DL_SUB_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getDlSubUpdateTime() {
        return dlSubUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_DIST_LINE.DL_SUB_UPDATE_TIME
     *
     * @param dlSubUpdateTime the value for BP_DIST_LINE.DL_SUB_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setDlSubUpdateTime(Date dlSubUpdateTime) {
        this.dlSubUpdateTime = dlSubUpdateTime;
    }
}