package com.icss.bp.dao;

import com.icss.bp.bean.BPDistLineBean;

public interface BPDistLineDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BP_DIST_LINE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long dlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BP_DIST_LINE
     *
     * @mbggenerated
     */
    int insert(BPDistLineBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BP_DIST_LINE
     *
     * @mbggenerated
     */
    int insertSelective(BPDistLineBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BP_DIST_LINE
     *
     * @mbggenerated
     */
    BPDistLineBean selectByPrimaryKey(Long dlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BP_DIST_LINE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BPDistLineBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BP_DIST_LINE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BPDistLineBean record);
}