package com.icss.bp.dao;

import com.icss.bp.bean.BPOrderBarcodeBean;

public interface BPOrderBarcodeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BP_ORDER_BARCODE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long obId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BP_ORDER_BARCODE
     *
     * @mbggenerated
     */
    int insert(BPOrderBarcodeBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BP_ORDER_BARCODE
     *
     * @mbggenerated
     */
    int insertSelective(BPOrderBarcodeBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BP_ORDER_BARCODE
     *
     * @mbggenerated
     */
    BPOrderBarcodeBean selectByPrimaryKey(Long obId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BP_ORDER_BARCODE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BPOrderBarcodeBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BP_ORDER_BARCODE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BPOrderBarcodeBean record);
}