package com.icss.bp.bean;

import java.util.Date;

public class BPBatchBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_ID
     *
     * @mbggenerated
     */
    private Long bId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_UUID
     *
     * @mbggenerated
     */
    private String bUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_SORT_DATE
     *
     * @mbggenerated
     */
    private Date bSortDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_CODE
     *
     * @mbggenerated
     */
    private String bCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_SEQUENCE
     *
     * @mbggenerated
     */
    private Integer bSequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_TYPE
     *
     * @mbggenerated
     */
    private String bType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_IS_CHANGE_SLINE
     *
     * @mbggenerated
     */
    private String bIsChangeSline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_SLINE_CODE
     *
     * @mbggenerated
     */
    private String bSlineCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_ORDER_NUM
     *
     * @mbggenerated
     */
    private Integer bOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_SHOULD_SEND_NUM
     *
     * @mbggenerated
     */
    private Integer bShouldSendNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_THIS_SEND_NUM
     *
     * @mbggenerated
     */
    private Integer bThisSendNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_ALL_RECV_NUM
     *
     * @mbggenerated
     */
    private Integer bAllRecvNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_PRINT_NUM
     *
     * @mbggenerated
     */
    private Integer bPrintNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_START_TIME
     *
     * @mbggenerated
     */
    private Date bStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_END_TIME
     *
     * @mbggenerated
     */
    private Date bEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_STATE
     *
     * @mbggenerated
     */
    private String bState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_SEND_STATE
     *
     * @mbggenerated
     */
    private String bSendState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_SELF_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date bSelfUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BP_BATCH.B_SUB_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date bSubUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_ID
     *
     * @return the value of BP_BATCH.B_ID
     *
     * @mbggenerated
     */
    public Long getbId() {
        return bId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_ID
     *
     * @param bId the value for BP_BATCH.B_ID
     *
     * @mbggenerated
     */
    public void setbId(Long bId) {
        this.bId = bId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_UUID
     *
     * @return the value of BP_BATCH.B_UUID
     *
     * @mbggenerated
     */
    public String getbUuid() {
        return bUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_UUID
     *
     * @param bUuid the value for BP_BATCH.B_UUID
     *
     * @mbggenerated
     */
    public void setbUuid(String bUuid) {
        this.bUuid = bUuid == null ? null : bUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_SORT_DATE
     *
     * @return the value of BP_BATCH.B_SORT_DATE
     *
     * @mbggenerated
     */
    public Date getbSortDate() {
        return bSortDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_SORT_DATE
     *
     * @param bSortDate the value for BP_BATCH.B_SORT_DATE
     *
     * @mbggenerated
     */
    public void setbSortDate(Date bSortDate) {
        this.bSortDate = bSortDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_CODE
     *
     * @return the value of BP_BATCH.B_CODE
     *
     * @mbggenerated
     */
    public String getbCode() {
        return bCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_CODE
     *
     * @param bCode the value for BP_BATCH.B_CODE
     *
     * @mbggenerated
     */
    public void setbCode(String bCode) {
        this.bCode = bCode == null ? null : bCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_SEQUENCE
     *
     * @return the value of BP_BATCH.B_SEQUENCE
     *
     * @mbggenerated
     */
    public Integer getbSequence() {
        return bSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_SEQUENCE
     *
     * @param bSequence the value for BP_BATCH.B_SEQUENCE
     *
     * @mbggenerated
     */
    public void setbSequence(Integer bSequence) {
        this.bSequence = bSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_TYPE
     *
     * @return the value of BP_BATCH.B_TYPE
     *
     * @mbggenerated
     */
    public String getbType() {
        return bType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_TYPE
     *
     * @param bType the value for BP_BATCH.B_TYPE
     *
     * @mbggenerated
     */
    public void setbType(String bType) {
        this.bType = bType == null ? null : bType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_IS_CHANGE_SLINE
     *
     * @return the value of BP_BATCH.B_IS_CHANGE_SLINE
     *
     * @mbggenerated
     */
    public String getbIsChangeSline() {
        return bIsChangeSline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_IS_CHANGE_SLINE
     *
     * @param bIsChangeSline the value for BP_BATCH.B_IS_CHANGE_SLINE
     *
     * @mbggenerated
     */
    public void setbIsChangeSline(String bIsChangeSline) {
        this.bIsChangeSline = bIsChangeSline == null ? null : bIsChangeSline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_SLINE_CODE
     *
     * @return the value of BP_BATCH.B_SLINE_CODE
     *
     * @mbggenerated
     */
    public String getbSlineCode() {
        return bSlineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_SLINE_CODE
     *
     * @param bSlineCode the value for BP_BATCH.B_SLINE_CODE
     *
     * @mbggenerated
     */
    public void setbSlineCode(String bSlineCode) {
        this.bSlineCode = bSlineCode == null ? null : bSlineCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_ORDER_NUM
     *
     * @return the value of BP_BATCH.B_ORDER_NUM
     *
     * @mbggenerated
     */
    public Integer getbOrderNum() {
        return bOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_ORDER_NUM
     *
     * @param bOrderNum the value for BP_BATCH.B_ORDER_NUM
     *
     * @mbggenerated
     */
    public void setbOrderNum(Integer bOrderNum) {
        this.bOrderNum = bOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_SHOULD_SEND_NUM
     *
     * @return the value of BP_BATCH.B_SHOULD_SEND_NUM
     *
     * @mbggenerated
     */
    public Integer getbShouldSendNum() {
        return bShouldSendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_SHOULD_SEND_NUM
     *
     * @param bShouldSendNum the value for BP_BATCH.B_SHOULD_SEND_NUM
     *
     * @mbggenerated
     */
    public void setbShouldSendNum(Integer bShouldSendNum) {
        this.bShouldSendNum = bShouldSendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_THIS_SEND_NUM
     *
     * @return the value of BP_BATCH.B_THIS_SEND_NUM
     *
     * @mbggenerated
     */
    public Integer getbThisSendNum() {
        return bThisSendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_THIS_SEND_NUM
     *
     * @param bThisSendNum the value for BP_BATCH.B_THIS_SEND_NUM
     *
     * @mbggenerated
     */
    public void setbThisSendNum(Integer bThisSendNum) {
        this.bThisSendNum = bThisSendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_ALL_RECV_NUM
     *
     * @return the value of BP_BATCH.B_ALL_RECV_NUM
     *
     * @mbggenerated
     */
    public Integer getbAllRecvNum() {
        return bAllRecvNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_ALL_RECV_NUM
     *
     * @param bAllRecvNum the value for BP_BATCH.B_ALL_RECV_NUM
     *
     * @mbggenerated
     */
    public void setbAllRecvNum(Integer bAllRecvNum) {
        this.bAllRecvNum = bAllRecvNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_PRINT_NUM
     *
     * @return the value of BP_BATCH.B_PRINT_NUM
     *
     * @mbggenerated
     */
    public Integer getbPrintNum() {
        return bPrintNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_PRINT_NUM
     *
     * @param bPrintNum the value for BP_BATCH.B_PRINT_NUM
     *
     * @mbggenerated
     */
    public void setbPrintNum(Integer bPrintNum) {
        this.bPrintNum = bPrintNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_START_TIME
     *
     * @return the value of BP_BATCH.B_START_TIME
     *
     * @mbggenerated
     */
    public Date getbStartTime() {
        return bStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_START_TIME
     *
     * @param bStartTime the value for BP_BATCH.B_START_TIME
     *
     * @mbggenerated
     */
    public void setbStartTime(Date bStartTime) {
        this.bStartTime = bStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_END_TIME
     *
     * @return the value of BP_BATCH.B_END_TIME
     *
     * @mbggenerated
     */
    public Date getbEndTime() {
        return bEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_END_TIME
     *
     * @param bEndTime the value for BP_BATCH.B_END_TIME
     *
     * @mbggenerated
     */
    public void setbEndTime(Date bEndTime) {
        this.bEndTime = bEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_STATE
     *
     * @return the value of BP_BATCH.B_STATE
     *
     * @mbggenerated
     */
    public String getbState() {
        return bState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_STATE
     *
     * @param bState the value for BP_BATCH.B_STATE
     *
     * @mbggenerated
     */
    public void setbState(String bState) {
        this.bState = bState == null ? null : bState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_SEND_STATE
     *
     * @return the value of BP_BATCH.B_SEND_STATE
     *
     * @mbggenerated
     */
    public String getbSendState() {
        return bSendState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_SEND_STATE
     *
     * @param bSendState the value for BP_BATCH.B_SEND_STATE
     *
     * @mbggenerated
     */
    public void setbSendState(String bSendState) {
        this.bSendState = bSendState == null ? null : bSendState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_SELF_UPDATE_TIME
     *
     * @return the value of BP_BATCH.B_SELF_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getbSelfUpdateTime() {
        return bSelfUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_SELF_UPDATE_TIME
     *
     * @param bSelfUpdateTime the value for BP_BATCH.B_SELF_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setbSelfUpdateTime(Date bSelfUpdateTime) {
        this.bSelfUpdateTime = bSelfUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BP_BATCH.B_SUB_UPDATE_TIME
     *
     * @return the value of BP_BATCH.B_SUB_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getbSubUpdateTime() {
        return bSubUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BP_BATCH.B_SUB_UPDATE_TIME
     *
     * @param bSubUpdateTime the value for BP_BATCH.B_SUB_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setbSubUpdateTime(Date bSubUpdateTime) {
        this.bSubUpdateTime = bSubUpdateTime;
    }

	@Override
	public String toString() {
		return "BPBatchBean [bId=" + bId + ", bUuid=" + bUuid + ", bSortDate="
				+ bSortDate + ", bCode=" + bCode + ", bSequence=" + bSequence
				+ ", bType=" + bType + ", bIsChangeSline=" + bIsChangeSline
				+ ", bSlineCode=" + bSlineCode + ", bOrderNum=" + bOrderNum
				+ ", bShouldSendNum=" + bShouldSendNum + ", bThisSendNum="
				+ bThisSendNum + ", bAllRecvNum=" + bAllRecvNum
				+ ", bPrintNum=" + bPrintNum + ", bStartTime=" + bStartTime
				+ ", bEndTime=" + bEndTime + ", bState=" + bState
				+ ", bSendState=" + bSendState + ", bSelfUpdateTime="
				+ bSelfUpdateTime + ", bSubUpdateTime=" + bSubUpdateTime + "]";
	}
    
    
}